# Generated by Django 5.2.3 on 2025-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationitem',
            name='file_url',
        ),
        migrations.AddField(
            model_name='educationitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='education_pdfs/'),
        ),
        migrations.AddField(
            model_name='educationitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('aparat', 'Aparat Link')], max_length=10),
        ),
    ]
