# Generated by Django 5.2.3 on 2025-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='allergies',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='diseases',
            new_name='disease_description',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='notes',
            new_name='doctor_observation_reason',
        ),
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مذکر'), ('female', 'مونث')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_autoimmune_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_bleeding_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_epilepsy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_hepatitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_history_of_hospitalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_lung_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_respiratory_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_in_menstrual_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='landline',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason_for_visit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='under_doctor_observation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='weeks_of_pregnancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
