# Generated by Django 5.2.3 on 2025-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_allergies_patient_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='disease_description',
            new_name='current_medications',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='has_autoimmune_disease',
            new_name='has_blood_disease',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='has_bleeding_disorder',
            new_name='has_tonsil_issue',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_observation_reason',
            new_name='other_diseases',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='reason_for_visit',
            new_name='problem_list',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='education',
            new_name='relationship_with_patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='father_name',
            new_name='relative_job',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='place_of_birth',
            new_name='system_used',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='has_epilepsy',
            new_name='treatment_consent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='has_hepatitis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='has_kidney_disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='has_respiratory_disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_in_menstrual_cycle',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='under_doctor_observation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weeks_of_pregnancy',
        ),
        migrations.AddField(
            model_name='patient',
            name='bite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='crowding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='dual_bite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='gingival_show',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='midline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='molars',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='protrusion_lips',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='record_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='record_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='retention_plan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6),
        ),
    ]
