# Generated by Django 5.2.3 on 2025-07-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_treatment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='predicted_start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
