# Generated by Django 5.2.3 on 2025-06-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=255)),
                ('total_amount', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('card', 'Card'), ('online', 'Online')], max_length=50)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
