# Generated by Django 5.2.3 on 2025-07-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_doctor_note'),
        ('payments', '0002_remove_payment_method_remove_payment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment'),
        ),
    ]
