# Generated by Django 5.2.3 on 2025-07-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_doctor_note'),
        ('payments', '0004_remove_payment_date_remove_payment_treatment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment'),
        ),
    ]
