# Generated by Django 5.2.3 on 2025-07-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_allergies_patient_address_and_more'),
        ('medicalfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_files/'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('xray', 'X-ray'), ('link', 'Link')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='accounts.patient'),
        ),
    ]
