# Generated by Django 5.2.3 on 2025-06-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='predicted_start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='actual_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='predicted_duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار'), ('in_progress', 'در حال درمان'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'کنسل\u200cشده'), ('absent', 'عدم حضور')], default='waiting', max_length=20),
        ),
    ]
