# Generated by Django 5.2.3 on 2025-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_actual_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
